# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.migration.version", 22);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140722064054");
user_pref("browser.slowStartup.averageTime", 1539);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20140722064054");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"webrtc-status-button\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"social-share-button\",\"action-button--jid1-vpn8dr0psezwzwjetpack-baidu-link\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"action-button--jid1-vpn8dr0psezwzwjetpack-baidu-link\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"newElementCount\":0}");
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1407420485950");
user_pref("datareporting.policy.firstRunTime", "1407334085950");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 55);
user_pref("datareporting.sessions.current.startTime", "1407334085586");
user_pref("datareporting.sessions.current.totalTime", 4);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-VPN8dr0PseZWzw@jetpack\":{\"version\":\"0.1\",\"type\":\"extension\",\"descriptor\":\"/home/acgotaku/Documents/firefox/sdk/my-addon/mozlia/extensions/jid1-VPN8dr0PseZWzw@jetpack.xpi\"}}");
user_pref("extensions.checkCompatibility.31.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1407142754000,\"rdfTime\":1406012265000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-VPN8dr0PseZWzw@jetpack\":{\"descriptor\":\"/home/acgotaku/Documents/firefox/sdk/my-addon/mozlia/extensions/jid1-VPN8dr0PseZWzw@jetpack.xpi\",\"mtime\":1407334085000}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk.console.logLevel", "info");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("gecko.buildID", "20140722064054");
user_pref("gecko.mstone", "31.0");
user_pref("javascript.options.strict", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1407334085);
user_pref("toolkit.telemetry.previousBuildID", "20140722064054");
user_pref("urlclassifier.updateinterval", 172800);
