name: Build

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.11.0

      - name: Set node version
        uses: actions/setup-node@v6
        with:
          node-version: '25.8.2'
          cache: 'pnpm'

      - name: Install CRX3 tools
        run: pip3 install crx3

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build 115
        run: pnpm build

      - name: Write pem to file
        run: |
          echo "$CHROME_PEM" > /tmp/chrome.pem
        env:
          CHROME_PEM: ${{ secrets.CHROME_PEM }}

      - name: Package 115
        run: |
          crx3 create dist -p /tmp/chrome.pem -o ./115.crx
          rm -rf release
          mv dist release
          mv 115.crx release

      - uses: EndBug/add-and-commit@v10
        with:
          add: "release"
          message: "[ci skip] update crx and release"
